//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProgramı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoklar
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public string Ozellik { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> Alis { get; set; }
        public Nullable<decimal> Satis { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string Barkod { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
